# [LAB-11] 데이터베이스 프로그래밍

## 2. 다중행 데이터 조회

### #01 데이터베이스 접속

1. 필요한 패키지 참조

In [1]:
from sqlalchemy import create_engine, text
from pandas import DataFrame

2. 접속 문자열 생성

In [2]:
config = {
    'username': 'root',         # 접속할 사용자 이름
    'password': '1234',         # 접속할 사용자의 비밀번호
    'hostname': 'localhost',    # 접속할 시스템 주소 (내 컴퓨터인 경우)
    'port': 9090,               # 설치 시 설정한 포트번호
    'database': 'myschool',     # 사용할 데이터베이스 이름
    'charset': 'utf8mb4'        # 한글 깨짐 방지
}

con_str_tpl = "mariadb+pymysql://{username}:{password}@{hostname}:{port}/{database}?charset={charset}"

con_str = con_str_tpl.format(**config)
print(con_str)

mariadb+pymysql://root:1234@localhost:9090/myschool?charset=utf8mb4

3. 데이터베이스에 접속하여 SQL 실행 객체 생성

In [3]:
try:
    engine = create_engine(con_str)         # con_str 은 직전 블록에서 생성한 변수를 재사용하고 있음
    conn = engine.connect()                 # 데이터베이스에 접속해 SQL 실행 객체를 리턴받는다
    print("Database connect success!!!")
except Exception as e:
    print("Database connect fail!!!", e)    # 예외 발생 시 에러 메시지를 참고해 접속 정보를 확인

Database connect success!!!

### #02 여러 행을 반환하는 SQL문 실행하기

1. 결과집합이 "딕셔너리를 포함하는 리스트" 형태로 반환

In [4]:
# SQL문 정의
sql = text("SELECT id, dname, loc, phone, email FROM departments ORDER BY id ASC LIMIT 0, 5")

try:
    result = conn.execute(sql)              # SQL문을 실행하여 결과 객체 받기
except Exception as e:
    print("[SQL Error]", e)                 # 코드의 진행을 중단시킴
    raise SystemExit

resultset = result.mappings().all()         # SQL문 실행 결과를 딕셔너리를 포함하는 리스트 형태로 변환
print(resultset)

[{'id': 101, 'dname': '컴퓨터공학과', 'loc': '공학관', 'phone': '051-123-4567', 'email': 'cs@myschool.ac.kr'}, {'id': 102, 'dname': '소프트웨어학과', 'loc': '공학관', 'phone': '051-124-4567', 'email': 'media@myschool.ac.kr'}, {'id': 201, 'dname': '전자공학과', 'loc': '공학관', 'phone': '051-125-4567', 'email': 'ee@myschool.ac.kr'}, {'id': 202, 'dname': '기계공학과', 'loc': '공학관', 'phone': '051-126-4567', 'email': 'me@myschool.ac.kr'}, {'id': 203, 'dname': '건축학과', 'loc': '건축관', 'phone': '051-127-4567', 'email': 'arch@myschool.ac.kr'}]

### #03 결과 집합 사용하기

1. 반복문을 활용한 데이터 출력

In [6]:
# 리스트의 길이는 조회된 결과 집합의 수
# `resultset`은 직접 코드 블록에서 생성한 객체
print("총 %d건의 데이터 조회됨" % len(resultset))

# 출력을 위한 문자열 템플릿
tmpl = "학과번호: {id}, 학과이름: {dname}, 위치: {loc}, 연락처: {phone}, 이메일: {email}"

# 반복문으로 문자열 포매팅을 수행하면서 개별 행을 하나씩 출력
for row in resultset:
    print(tmpl.format(**row))

총 5건의 데이터 조회됨
학과번호: 101, 학과이름: 컴퓨터공학과, 위치: 공학관, 연락처: 051-123-4567, 이메일: cs@myschool.ac.kr
학과번호: 102, 학과이름: 소프트웨어학과, 위치: 공학관, 연락처: 051-124-4567, 이메일: media@myschool.ac.kr
학과번호: 201, 학과이름: 전자공학과, 위치: 공학관, 연락처: 051-125-4567, 이메일: ee@myschool.ac.kr
학과번호: 202, 학과이름: 기계공학과, 위치: 공학관, 연락처: 051-126-4567, 이메일: me@myschool.ac.kr
학과번호: 203, 학과이름: 건축학과, 위치: 건축관, 연락처: 051-127-4567, 이메일: arch@myschool.ac.kr

2. 결과 집합을 표 형태로 반환

In [7]:
# `resultset`은 직전 코드 블록에서 사용한 객체를 재사용함
df1 = DataFrame(resultset)

# Python 출력문으로 출력하기
print(df1)

    id    dname  loc         phone                 email
0  101   컴퓨터공학과  공학관  051-123-4567     cs@myschool.ac.kr
1  102  소프트웨어학과  공학관  051-124-4567  media@myschool.ac.kr
2  201    전자공학과  공학관  051-125-4567     ee@myschool.ac.kr
3  202    기계공학과  공학관  051-126-4567     me@myschool.ac.kr
4  203     건축학과  건축관  051-127-4567   arch@myschool.ac.kr

3. Jupyter의 고유 기능을 활용해 표 형태로 출력

In [8]:
# `resultset`은 직전 코드 블록에서 사용한 객체를 재사용함
df2 = DataFrame(resultset)

# Python 출력문으로 출력하기
df2

    id    dname  loc         phone                 email
0  101   컴퓨터공학과  공학관  051-123-4567     cs@myschool.ac.kr
1  102  소프트웨어학과  공학관  051-124-4567  media@myschool.ac.kr
2  201    전자공학과  공학관  051-125-4567     ee@myschool.ac.kr
3  202    기계공학과  공학관  051-126-4567     me@myschool.ac.kr
4  203     건축학과  건축관  051-127-4567   arch@myschool.ac.kr

### #04 입력값에 따른 검색 결과 만들기

In [9]:
# 검색어
keyword = input("검색할 교수 이름을 입력하세요.")

# SQL문 정의
sql = text("""SELECT p.id AS 교수번호,
                     name AS 이름,
                     position AS 직급,
                     sal AS 급여,
                     comm AS 보직수당,
                     hiredate AS 입사일시,
                     dname AS 소속학과
            FROM professors p
            INNER JOIN departments d ON p.department_id = d.id
            WHERE name LIKE concat('%', :keyword, '%')""")

# SQL문 실행하기
try:
    result = conn.execute(sql, {"keyword": keyword})
except Exception as e:
    print("[SQL Error]", e)                 # 코드의 진행을 중단시킴
    raise SystemExit

# 조회결과를 표로 출력
resultset = result.mappings().all()         # SQL문 실행 결과를 딕셔너리를 포함하는 리스트 형태로 변환
df = DataFrame(resultset)
df

   교수번호   이름   직급   급여  보직수당                입사일시     소속학과
0  9906  김현주   교수  300  21.0 2006-08-31 01:04:24  소프트웨어학과
1  9909  김정훈   교수  392  24.0 2001-09-09 07:36:05    전자공학과
2  9914  김지아  조교수  385   NaN 2002-08-06 23:35:57     건축학과
3  9926  김정웅  조교수  253   NaN 2012-07-24 21:27:58     심리학과

### #05 Pandas 활용 데이터 조회

1. 필요한 패키지 참조하기

In [10]:
from pandas import read_sql

2. SQL문의 결과를 표 형채로 직접 가져오기

In [11]:
sql = text("SELECT id, name, position, sal, comm FROM professors WHERE sal > 500")

try:
    df = read_sql(sql, conn)               # SQL문과 SQLAlchemy의 접속 객체를 파라미터로 전달해 데이터프레임 즉시 생성
except Exception as e:
    print("SQL Error:", e)                 # 코드의 진행을 중단시킴
    raise SystemExit

df

     id name position  sal  comm
0  9902  허경희     전임강사  552   NaN
1  9903  전종수      조교수  508   NaN
2  9910  강영호      조교수  593   NaN
3  9915  이옥순       교수  548  22.0
4  9918  오미영      부교수  578   NaN
5  9928  이영길      조교수  526  14.0
6  9931  최정훈      부교수  520   NaN

3. 입력값을 활용한 검색 범위 만들기

In [12]:
min_height = int(input("키의 하한값을 입력하세요."))
max_height = int(input("키의 상한값을 입력하세요."))

sql = text("""SELECT id, name, grade, height, weight, gender
            FROM students
            WHERE height BETWEEN :min AND :max""")

try:
    df = read_sql(sql, conn, params = {"min": min_height, "max": max_height})
except Exception as e:
    print("SQL Error", e)                 # 코드의 진행을 중단시킴
    raise SystemExit

df

       id name  grade  height  weight gender
0   10103  백순옥      2     184      71      남
1   10106  서현지      1     185      63      여
2   10109  안서윤      2     184      60      남
3   10114  김명숙      4     188      49      여
4   10118  강지우      3     181      46      남
5   10122  이순자      4     183      73      남
6   10123  김병철      2     187      59      남
7   10128  이지원      4     185      51      남
8   10134  이민영      1     189      50      여
9   10138  홍지후      1     185      64      남
10  10150  양도윤      4     188      77      남
11  10152  민지민      3     182      64      여
12  10157  백승현      2     180      84      남
13  10165  박은영      4     180      45      여
14  10166  이주원      2     181      59      여
15  10175  문은서      1     186      47      여
16  10180  김하늘      3     180     120    NaN

4. CSV 파일로 저장하기

In [13]:
df.to_csv("학생목록.csv", encoding="utf-8")

5. 엑셀 파일로 저장하기

In [14]:
df.to_excel("학생목록.xlsx")